### ISSUE TITLE
Projection misses state updated when going back and forth between deposits and withdrawals

### ISSUE THREAD

**Issue by 4deeptech** [trbngr/AkkaCqrs#1]
Been looking through this to see how you set things up and playing with it.  I came across an issue where the deposit misses out on withdrawals so it still has the prior balance.  I deposited a couple times say 500 a couple times where the balance is 1000.  The json file written out has 1000.  If I withdraw 1000 then the file says 0, however the depositmade actor still has 1000 as it's balance internally (which should be 0) since it does not reread state from storage.  If you then issue a deposit of say 500 the state gets written out as 1500 because it did not know about the withdrawal.  Still trying to learn akka so trying to decide what the best way is to handle this.  I am guessing there should not be separate actors for the account projection events.

**Comment by trbngr** [comment]
Sorry for the delay. I've been off the computer for a week.

I'll have a look.

**Comment by trbngr** [comment]
I've pushed the fix [here](https://github.com/trbngr/AkkaCqrs/commit/ec58b3200a8c7db02a47741e766c68f1cb12be0d#diff-d38d419d4dfd8188b97c7d440594fdeaR52).

Basically, the projections never retrieved the read-model again, after the first time. So the _entity was in-mem and being reused over and over again.

Also, there seems to be a bug writing the file when the balance goes to zero. Very strange.

But, this is just an exercise for me beginning Akka.net. I don't have time to fix it.

-=Chris

**Comment by 4deeptech** [comment]
Understood and figured that was the case. I have been working on a persistence provider for Azure Table Storage that I have wired into the sample and been playing around with various ideas about using Akka.net for event sourced components.  Your thing was a good start. Thanks

**Comment by trbngr** [comment]
Glad I could help.

If you have a repo, I'd love to see where you're heading.
